# file: secret_config.yaml

jupyterhub:
  proxy:
    secretToken: "<SECRET>"

  # comment this out if not using github authentication
  auth:
    type: github
    github:
      clientId: "<CLIENTID>"
      clientSecret: "<CLIENT_SECRET>"
      callbackUrl: "http://<IP_OR_DOMAIN>/hub/oauth_callback"
      org_whitelist:
        - "your_github_org"
        - "pangeo-data"
    scopes:
      - "read:user"
    admin:
      access: true
      users:
        - admin_user_1
        - admin_user_2
